language: cpp

compiler:
  - gcc
  - clang

env:
  - M3CORE_BUILD_TYPE=Debug
  - M3CORE_BUILD_TYPE=Release

before_script:
  - sudo apt-get install -qq libqt4-dev moc g++ libncurses5-dev kernel-package gcc-multilib libc6-dev libtool automake cmake git openssh-server openssh-client libyaml-cpp0.3-dev libeigen3-dev libprotobuf-dev protobuf-compiler gnuplot-x11 libyaml-cpp0.3-dev libboost-dev protobuf-compiler python-dev libprotobuf-dev python-protobuf python-matplotlib python-yaml python-gnuplot python-scipy python-sip-dev python-sip sip-dev


script:
  #build m3core
  - cd m3core
  - mkdir build
  - cd build
  - cmake -DETHERCAT=0 -DROS=0 -DRTAI=0 -DCMAKE_BUILD_TYPE=${M3CORE_BUILD_TYPE} ..
  # compile and install m3core
  - make
  - sudo make install
