language: cpp

compiler:
  - gcc
  - clang

env:
  - M3CORE_BUILD_TYPE=Debug
  - M3CORE_BUILD_TYPE=Release
  - RTAI=OFF
  - RTAI=ON

before_script:
  - sudo apt-get install -qq moc cmake libeigen3-dev libprotobuf-dev protobuf-compiler libboost-dev python-dev python-protobuf python-matplotlib python-yaml python-gnuplot python-scipy python-sip-dev python-sip
  #- wget http://perso.ensta-paristech.fr/~hoarau/rtmeka-kern/$(uname -p)/linux-image-rt.deb
  #- sudo dpkg -i linux-headers-rt.deb 
  #- sudo dpkg -i linux-image-rt.deb
  ### Get the kernel dir from the debian
  #- rtkernel=$(dpkg-deb --info linux-headers-rt.deb |grep Package -m 1 | grep -Po "linux-headers-\K(.*)")
  #build m3core
  - cd m3core
  - mkdir build
  - cd build
  - cmake -DETHERCAT=0 -DROS=0 -DRTAI=0 -DCMAKE_BUILD_TYPE=${M3CORE_BUILD_TYPE} ...#-DKERNEL_NAME=$rtkernel..
  
script:
  # compile and install m3core
  - make -j5
  - sudo make install
