# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_M3COMP_STATE = descriptor.EnumDescriptor(
  name='M3COMP_STATE',
  full_name='M3COMP_STATE',
  filename='M3COMP_STATE',
  values=[
    descriptor.EnumValueDescriptor(
      name='M3COMP_STATE_INIT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='M3COMP_STATE_ERR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='M3COMP_STATE_SAFEOP', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='M3COMP_STATE_OP', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


M3COMP_STATE_INIT = 0
M3COMP_STATE_ERR = 1
M3COMP_STATE_SAFEOP = 2
M3COMP_STATE_OP = 3



_M3STATUSALL = descriptor.Descriptor(
  name='M3StatusAll',
  full_name='M3StatusAll',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='M3StatusAll.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datum', full_name='M3StatusAll.datum', index=1,
      number=2, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3COMMANDALL = descriptor.Descriptor(
  name='M3CommandAll',
  full_name='M3CommandAll',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name_cmd', full_name='M3CommandAll.name_cmd', index=0,
      number=1, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name_param', full_name='M3CommandAll.name_param', index=1,
      number=2, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datum_cmd', full_name='M3CommandAll.datum_cmd', index=2,
      number=3, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='datum_param', full_name='M3CommandAll.datum_param', index=3,
      number=4, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3STATUSLOGPAGE = descriptor.Descriptor(
  name='M3StatusLogPage',
  full_name='M3StatusLogPage',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entry', full_name='M3StatusLogPage.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3BASESTATUS = descriptor.Descriptor(
  name='M3BaseStatus',
  full_name='M3BaseStatus',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='M3BaseStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='M3BaseStatus.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3BaseStatus.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rate', full_name='M3BaseStatus.rate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("fast", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='M3BaseStatus.version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3ETHERCATSTATUS = descriptor.Descriptor(
  name='M3EtherCATStatus',
  full_name='M3EtherCATStatus',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='network_id', full_name='M3EtherCATStatus.network_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serial_number', full_name='M3EtherCATStatus.serial_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='product_code', full_name='M3EtherCATStatus.product_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='active', full_name='M3EtherCATStatus.active', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='online', full_name='M3EtherCATStatus.online', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operational', full_name='M3EtherCATStatus.operational', index=5,
      number=6, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='al_state', full_name='M3EtherCATStatus.al_state', index=6,
      number=7, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pdo_version', full_name='M3EtherCATStatus.pdo_version', index=7,
      number=20, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3MONITORCOMPONENT = descriptor.Descriptor(
  name='M3MonitorComponent',
  full_name='M3MonitorComponent',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='M3MonitorComponent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='M3MonitorComponent.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_time_status_us', full_name='M3MonitorComponent.cycle_time_status_us', index=2,
      number=3, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_time_command_us', full_name='M3MonitorComponent.cycle_time_command_us', index=3,
      number=4, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3MONITORCOMMAND = descriptor.Descriptor(
  name='M3MonitorCommand',
  full_name='M3MonitorCommand',
  filename='component_base.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3MONITORPARAM = descriptor.Descriptor(
  name='M3MonitorParam',
  full_name='M3MonitorParam',
  filename='component_base.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3MONITORSTATUS = descriptor.Descriptor(
  name='M3MonitorStatus',
  full_name='M3MonitorStatus',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3MonitorStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_components_rt', full_name='M3MonitorStatus.num_components_rt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_components_ec', full_name='M3MonitorStatus.num_components_ec', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_components', full_name='M3MonitorStatus.num_components', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_components_safeop', full_name='M3MonitorStatus.num_components_safeop', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_components_op', full_name='M3MonitorStatus.num_components_op', index=5,
      number=6, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_components_err', full_name='M3MonitorStatus.num_components_err', index=6,
      number=7, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operational', full_name='M3MonitorStatus.operational', index=7,
      number=8, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_time_status_us', full_name='M3MonitorStatus.cycle_time_status_us', index=8,
      number=9, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_time_command_us', full_name='M3MonitorStatus.cycle_time_command_us', index=9,
      number=10, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_time_us', full_name='M3MonitorStatus.cycle_time_us', index=10,
      number=11, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_frequency_hz', full_name='M3MonitorStatus.cycle_frequency_hz', index=11,
      number=12, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='components', full_name='M3MonitorStatus.components', index=12,
      number=13, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_ethercat_cycles', full_name='M3MonitorStatus.num_ethercat_cycles', index=13,
      number=14, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cycle_time_max_us', full_name='M3MonitorStatus.cycle_time_max_us', index=14,
      number=15, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ec_domains', full_name='M3MonitorStatus.ec_domains', index=15,
      number=16, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3MONITORECDOMAIN = descriptor.Descriptor(
  name='M3MonitorEcDomain',
  full_name='M3MonitorEcDomain',
  filename='component_base.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='t_ecat_wait_rx', full_name='M3MonitorEcDomain.t_ecat_wait_rx', index=0,
      number=1, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='t_ecat_rx', full_name='M3MonitorEcDomain.t_ecat_rx', index=1,
      number=2, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='t_ecat_wait_shm', full_name='M3MonitorEcDomain.t_ecat_wait_shm', index=2,
      number=3, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='t_ecat_shm', full_name='M3MonitorEcDomain.t_ecat_shm', index=3,
      number=4, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='t_ecat_wait_tx', full_name='M3MonitorEcDomain.t_ecat_wait_tx', index=4,
      number=5, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='t_ecat_tx', full_name='M3MonitorEcDomain.t_ecat_tx', index=5,
      number=6, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3STATUSLOGPAGE.fields_by_name['entry'].message_type = _M3STATUSALL
_M3BASESTATUS.fields_by_name['state'].enum_type = _M3COMP_STATE
_M3MONITORCOMPONENT.fields_by_name['state'].enum_type = _M3COMP_STATE
_M3MONITORSTATUS.fields_by_name['base'].message_type = _M3BASESTATUS
_M3MONITORSTATUS.fields_by_name['components'].message_type = _M3MONITORCOMPONENT
_M3MONITORSTATUS.fields_by_name['ec_domains'].message_type = _M3MONITORECDOMAIN

class M3StatusAll(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3STATUSALL

class M3CommandAll(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3COMMANDALL

class M3StatusLogPage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3STATUSLOGPAGE

class M3BaseStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3BASESTATUS

class M3EtherCATStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3ETHERCATSTATUS

class M3MonitorComponent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3MONITORCOMPONENT

class M3MonitorCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3MONITORCOMMAND

class M3MonitorParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3MONITORPARAM

class M3MonitorStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3MONITORSTATUS

class M3MonitorEcDomain(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3MONITORECDOMAIN

