#!/bin/sh
if [ "${UID}" != 0 ]; then SUDO="sudo "; else SUDO=""; fi

#if test \! -c /dev/rtai_shm; then
#	$SUDO mknod -m 666 /dev/rtai_shm c 10 254
#fi
#for n in `seq 0 9`; do
#	f=/dev/rtf$n
#	if test \! -c $f; then
#		$SUDO mknod -m 666 $f c 150 $n
#	fi
#done

insmod=/sbin/insmod
rmmod=/sbin/rmmod
m3ko=/lib/modules/$(uname -r)/extra/m3ec.ko
MODULES=/usr/realtime/modules


if [ -f $MODULES/rtai_smi.ko ]
then
  sync
  $SUDO $insmod $MODULES/rtai_smi.ko;
  echo 'Inserting rtai_smi'
fi


#sync paranoia might be useful
echo 'Inserting rtai_hal'
sync
$SUDO $insmod $MODULES/rtai_hal.ko #IsolCpusMask=0; <- Deprecated with rtai 4.1

echo 'Inserting rtai_sched'
sync
$SUDO $insmod $MODULES/rtai_sched.ko;

echo 'Inserting rtai_sem'
sync
$SUDO $insmod $MODULES/rtai_sem.ko;

echo 'Inserting rtai_shm'
sync
$SUDO $insmod $MODULES/rtai_shm.ko;

echo 'Inserting rtai_wd'
sync
$SUDO $insmod $MODULES/rtai_wd.ko Policy=5; #1=RESYNC, 5=SUSPEND Policy.

sync
echo 'Inserting m3ec'
$SUDO $insmod $m3ko;
sync

